import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  login: true,
  currency: "Vnđ",
  overlay: false,
  danhMuc: [
    {
      ten: "Architecture",
      products: [
        {
          proName: "yến house",
          title: "Architecture, Interior",
          img: "",
          project: "",
          allPhotp: [],
          detail: "",
        },
        {
          proName: "tropical house",
          title: "Architecture, Interior",
          img: "",
          project: "",
          allPhotp: [],
          detail: "",
        },
        {
          proName: "thiết kế cafe sân vườn",
          title: "Architecture, Landscape",
          img: "",
          project: "",
          allPhotp: [],
          detail: "",
        },
        {
          proName: "cải tạo nhà phố tiền giang",
          title: "Architecture, Interior",
          img: "",
          project: "",
          allPhotp: [],
          detail: "",
        },
        {
          proName: "nhà phố gò vấp",
          title: "Architecture, Interior",
          img: "",
          project: "",
          allPhotp: [],
          detail: "",
        },
        {
          proName: "chi house - nhà cải tạo biên hòa",
          title: "Architecture, Interior",
          img: "",
          project: "",
          allPhotp: [],
          detail: "",
        },
        {
          proName: "nhà bình dương",
          title: "Architecture, Interior",
          img: "",
          project: "",
          allPhotp: [],
          detail: "",
        },
        {
          proName: "căn hộ industrial",
          title: "Architecture, Interior",
          img: "",
          project: "",
          allPhotp: [],
          detail: "",
        },
      ],
    },
    {
      ten: "Interior",
      products: [
        {
          proName: "yến house",
          title: "Architecture, Interior",
          img: "",
          project: "",
          allPhotp: [],
          detail: "",
        },
        {
          proName: "tropical house",
          title: "Architecture, Interior",
          img: "",
          project: "",
          allPhotp: [],
          detail: "",
        },
        {
          proName: "căn hộ the peak midtown",
          title: "Interior",
          img: "",
          project: "",
          allPhotp: [],
          detail: "",
        },
        {
          proName: "cải tạo nhà phố tiền giang",
          title: "Architecture, Interior",
          img: "",
          project: "",
          allPhotp: [],
          detail: "",
        },
        {
          proName: "nhà phố gò vấp",
          title: "Architecture, Interior",
          img: "",
          project: "",
          allPhotp: [],
          detail: "",
        },
        {
          proName: "nhà của gạo",
          title: "Interior",
          img: "",
          project: "",
          allPhotp: [],
          detail: "",
        },
        {
          proName: "chi house - nhà cải tạo biên hòa",
          title: "Architecture, Interior",
          img: "",
          project: "",
          allPhotp: [],
          detail: "",
        },
        {
          proName: "nhà bình dương",
          title: "Architecture, Interior",
          img: "",
          project: "",
          allPhotp: [],
          detail: "",
        },
        {
          proName: "căn hộ lavida plus",
          title: "Interior",
          img: "",
          project: "",
          allPhotp: [],
          detail: "",
        },
        {
          proName: "căn hộ 50M2 lavida plus",
          title: "Interior",
          img: "",
          project: "",
          allPhotp: [],
          detail: "",
        },
        {
          proName: "căn hộ him lam chợ lớn",
          title: "Interior",
          img: "",
          project: "",
          allPhotp: [],
          detail: "",
        },
        {
          proName: "căn hộ flora fuji",
          title: "Interior",
          img: "",
          project: "",
          allPhotp: [],
          detail: "",
        },
        {
          proName: "căn hộ industrial",
          title: "Architecture, Interior",
          img: "",
          project: "",
          allPhotp: [],
          detail: "",
        },

        {
          proName: "căn hộ 75M2",
          title: "Interior",
          img: "",
          project: "",
          allPhotp: [],
          detail: "",
        },
        {
          proName: "căn hộ 2 phòng ngủ quận 6",
          title: "Interior",
          img: "",
          project: "",
          allPhotp: [],
          detail: "",
        },
      ],
    },
    {
      ten: "Landscape",
      products: [
        {
          proName: "thiết kế cafe sân vườn",
          title: "Landscape",
          img: "",
          project: "",
          allPhotp: [],
        },
      ],
    },
  ],

  products: [
    {
      proName: "yến house",
      title: "Architecture, Interior",
      img: "",
      project: "",
      allPhotp: [],
      detail: "",
      categories: ["Architecture", "Interior"],
    },
    {
      proName: "tropical house",
      title: "Architecture, Interior",
      img: "",
      project: "",
      allPhotp: [],
      detail: "",
      categories: ["Architecture", "Interior"],
    },
    {
      proName: "thiết kế cafe sân vườn",
      title: "Architecture, Landscape",
      img: "",
      project: "",
      allPhotp: [],
      detail: "",
      categories: ["Architecture", "Landscape"],
    },
    {
      proName: "cải tạo nhà phố tiền giang",
      title: "Architecture, Interior",
      img: "",
      project: "",
      allPhotp: [],
      detail: "",
      categories: ["Architecture", "Interior"],
    },
    {
      proName: "nhà phố gò vấp",
      title: "Architecture, Interior",
      img: "",
      project: "",
      allPhotp: [],
      detail: "",
      categories: ["Architecture", "Interior"],
    },
    {
      proName: "chi house - nhà cải tạo biên hòa",
      title: "Architecture, Interior",
      img: "",
      project: "",
      allPhotp: [],
      detail: "",
      categories: ["Architecture", "Interior"],
    },
    {
      proName: "nhà bình dương",
      title: "Architecture, Interior",
      img: "",
      project: "",
      allPhotp: [],
      detail: "",
      categories: ["Architecture", "Interior"],
    },
    {
      proName: "căn hộ industrial",
      title: "Architecture, Interior",
      img: "",
      project: "",
      allPhotp: [],
      detail: "",
      categories: ["Architecture", "Interior"],
    },
    {
      proName: "căn hộ the peak midtown",
      title: "Interior",
      img: "",
      project: "",
      allPhotp: [],
      detail: "",
      categories: ["Interior"],
    },
    {
      proName: "nhà của gạo",
      title: "Interior",
      img: "",
      project: "",
      allPhotp: [],
      detail: "",
      categories: ["Interior"],
    },
    {
      proName: "căn hộ lavida plus",
      title: "Interior",
      img: "",
      project: "",
      allPhotp: [],
      detail: "",
      categories: ["Interior"],
    },
    {
      proName: "căn hộ 50M2 lavida plus",
      title: "Interior",
      img: "",
      project: "",
      allPhotp: [],
      detail: "",
      categories: ["Interior"],
    },
    {
      proName: "căn hộ him lam chợ lớn",
      title: "Interior",
      img: "",
      project: "",
      allPhotp: [],
      detail: "",
      categories: ["Interior"],
    },
    {
      proName: "căn hộ flora fuji",
      title: "Interior",
      img: "",
      project: "",
      allPhotp: [],
      detail: "",
      categories: ["Interior"],
    },
    {
      proName: "căn hộ 75M2",
      title: "Interior",
      img: "",
      project: "",
      allPhotp: [],
      detail: "",
      categories: ["Interior"],
    },
    {
      proName: "căn hộ 2 phòng ngủ quận 6",
      title: "Interior",
      img: "",
      project: "",
      allPhotp: [],
      detail: "",
      categories: ["Interior"],
    },
  ],
};

const dataSlice = createSlice({
  name: "data",
  initialState,
  reducers: {
    updateLogin(state, action) {
      state.login = action.payload;
    },
    updateOverlay(state, action) {
      state.overlay = action.payload;
    },
  },
});

export const { updateLogin, updateOverlay } = dataSlice.actions;
export default dataSlice.reducer;
