import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  login: true,
  currency: "Vnđ",
  overlay: false,

  products: [
    {
      ma: "Q3_001",
      proName: "Nhà mặt tiền Quận 3",
      title: "28 Trần quốc thảo",
      address: "28 Trần Quốc Thảo, Phường Xuân Hoà(P6,Q3),Thành Phố Hồ Chí Minh",
      dienTich: "Ngang 4.5m x  Dài 43m NH 20m, công nhận 553m², DTS gần 2.000m²",
      ketCau: "Hầm 7 tầng ST",
      giaBan: "350 tỷ",
      hopDong: "800 triệu",
      huong: "Đông Nam",
      phapLy: "CTCP bán 100%",
      viTri: "Giữa Ngô Thời Nhiệm và Nguyễn Đình Chiểu",
      allPhoto: ["Q3_001_1.jpg", "Q3_001_2.jpg", "Q3_001_3.jpg"],
      categories: ["Nhà phố"],
    },
    {
      ma: "Q3_0011",
      proName: "Nhà mặt tiền Quận 3",
      title: "112Trần quốc thảo",
      address: "112 Trần Quốc Thảo, Phường Xuân Hoà(P6,Q3), Thành Phố Hồ Chí Minh",
      dienTich: "Ngang 14m x Dàì 28m, công nhận 412,09m², DTS 1006,8m²",
      ketCau: "Hầm + 4 tầng ST",
      giaBan: "330 tỷ",
      hopDong: "450 triệu",
      huong: "Tây Nam",
      phapLy: "Sổ hồng - Quyền sử dụng nhà và đất",
      viTri: "Giữa Trần Quốc Thảo và Lý Chính Thắng",
      allPhoto: ["Q3_001_1.jpg", "Q3_001_2.jpg", "Q3_001_3.jpg"],
      categories: ["Nhà phố"],
    },
    {
      ma: "Q1__002",
      
      proName: "Bán nhà 2 Bis Công Trường Quốc Tế",
      title: "2 Bis Công Trường Quốc Tế",
      address: "2 Bis Công Trường Quốc Tế, Phường Xuân Hoà(P6,Q3), Thành Phố Hồ Chí Minh",
      dienTich: " Ngang 15m x Dài 26m , công nhận 366,2m², DTS: 2316m²",
      ketCau: "2 hầm + 8 tầng, 1 ST",
      giaBan: "700 tỷ",
      hopDong: "1,5 tỷ",
      huong: "Tây Bắc",
      phapLy: "Sổ hồng - Quyền sử dụng nhà và đất ",
      viTri: "Góc 2 mặt tiền 2 Bis Công Trường Quốc Tế & Trần Cao Vân,",
      allPhoto: ["Q3_001_1.jpg", "Q3_001_2.jpg", "Q3_001_3.jpg"],
      categories: ["Biệt thự"],
    },
    {
      ma: "Q1_003",
      proName: "Building Nguyễn Thị Minh Khai",
      title: "10A Nguyễn Thị Minh Khai",
      address: "10A Nguyễn Thị Minh Khai,Phường Sài Gòn(Bến Nghé Quận 1), Thành Phố Hồ Chí Minh",
      dienTich: "Ngang 18 x Dài 18m, công nhận 190m, DTS: 2200m²",
      ketCau: "Hầm, 10 tầng",
      giaBan: "330 tỷ",
      hopDong: "600 triệu",
      huong: "",
      phapLy: "Sổ hồng - Quyền sử dụng nhà và đất",
      viTri: "Nguyễn Thị Minh Khai, Nguyễn Bỉnh Khiêm",
      allPhoto: ["Q1_BQ001_1.jpg", "Q1_BQ001_2.jpg", "Q1_BQ001_3.jpg"],
      categories: ["Building"],
    },
    {
      ma: "Q1_004",
      proName: "Building ách Mạng Tháng 8",
      title: "546 - 548 Cách Mạng Tháng 8",
      address: "546 - 548 Cách Mạng Tháng 8, Phường Nhiêu Lộc(p11 q3), Thành Phố Hồ Chí Minh",
      dienTich: " Ngang 15m x Dài 36m, nở hậu 26m, công nhận 668m², DTS: 5232.5m²",
      ketCau: "Hầm, 10 tầng",
      giaBan: " tỷ",
      hopDong: "1 tỷ",
      huong: "Tây Bắc",
      phapLy: "Sổ hồng - Quyền sử dụng nhà và đất",
      viTri: "Nguyễn Thị Minh Khai, Nguyễn Bỉnh Khiêm",
      allPhoto: ["Q1_BQ001_1.jpg", "Q1_BQ001_2.jpg", "Q1_BQ001_3.jpg"],
      categories: ["Building"],
    },
    {
      ma: "Q1_BQ0023",
      proName: "Building Nguyễn Thị Minh Khai",
      title: "Nguyễn Thị Minh Khai",
      address: "10A Nguyễn Thị Minh Khai, Quận 1, Thành Phố Hồ Chí Minh",
      dienTich: "18 x 18m, công nhận 190m2",
      ketCau: "Hầm, 10 tầng",
      giaBan: "330 tỷ",
      hopDong: "1 tỷ",
      huong: "",
      phapLy: "Cá nhân",
      viTri: "Nguyễn Thị Minh Khai, Nguyễn Bỉnh Khiêm",
      allPhoto: ["Q1_BQ001_1.jpg", "Q1_BQ001_2.jpg", "Q1_BQ001_3.jpg"],
      categories: ["Building"],
    },
   
     {
      ma: "Q1_BQ0023",
      proName: "Building Nguyễn Thị Minh Khai",
      title: "Nguyễn Thị Minh Khai",
      address: "10A Nguyễn Thị Minh Khai, Quận 1, Thành Phố Hồ Chí Minh",
      dienTich: "18 x 18m, công nhận 190m2",
      ketCau: "Hầm, 10 tầng",
      giaBan: "330 tỷ",
      hopDong: "1 tỷ",
      huong: "",
      phapLy: "Cá nhân",
      viTri: "Nguyễn Thị Minh Khai, Nguyễn Bỉnh Khiêm",
      allPhoto: ["Q1_BQ001_1.jpg", "Q1_BQ001_2.jpg", "Q1_BQ001_3.jpg"],
      categories: ["Building"],
    },
     {
      ma: "Q1_BQ0023",
      proName: "Building Nguyễn Thị Minh Khai",
      title: "Nguyễn Thị Minh Khai",
      address: "10A Nguyễn Thị Minh Khai, Quận 1, Thành Phố Hồ Chí Minh",
      dienTich: "18 x 18m, công nhận 190m2",
      ketCau: "Hầm, 10 tầng",
      giaBan: "330 tỷ",
      hopDong: "1 tỷ",
      huong: "",
      phapLy: "Cá nhân",
      viTri: "Nguyễn Thị Minh Khai, Nguyễn Bỉnh Khiêm",
      allPhoto: ["Q1_BQ001_1.jpg", "Q1_BQ001_2.jpg", "Q1_BQ001_3.jpg"],
      categories: ["Building"],
    },
    {
      ma: "Q1_BQ00233",
      proName: "Building Nguyễn Thị Minh Khai",
      title: "Nguyễn Thị Minh Khai",
      address: "10A Nguyễn Thị Minh Khai, Quận 1, Thành Phố Hồ Chí Minh",
      dienTich: "18 x 18m, công nhận 190m2",
      ketCau: "Hầm, 10 tầng",
      giaBan: "330 tỷ",
      hopDong: "1 tỷ",
      huong: "",
      phapLy: "Cá nhân",
      viTri: "Nguyễn Thị Minh Khai, Nguyễn Bỉnh Khiêm",
      allPhoto: ["Q1_BQ001_1.jpg", "Q1_BQ001_2.jpg", "Q1_BQ001_3.jpg"],
      categories: ["Building"],
    },
    {
      ma: "Q1_BQ00213",
      proName: "Building Nguyễn Thị Minh Khai",
      title: "Nguyễn Thị Minh Khai",
      address: "10A Nguyễn Thị Minh Khai, Quận 1, Thành Phố Hồ Chí Minh",
      dienTich: "18 x 18m, công nhận 190m2",
      ketCau: "Hầm, 10 tầng",
      giaBan: "330 tỷ",
      hopDong: "1 tỷ",
      huong: "",
      phapLy: "Cá nhân",
      viTri: "Nguyễn Thị Minh Khai, Nguyễn Bỉnh Khiêm",
      allPhoto: ["Q1_BQ001_1.jpg", "Q1_BQ001_2.jpg", "Q1_BQ001_3.jpg"],
      categories: ["Building"],
    },
  ],
};

const dataSlice = createSlice({
  name: "data",
  initialState,
  reducers: {
    updateLogin(state, action) {
      state.login = action.payload;
    },
    updateOverlay(state, action) {
      state.overlay = action.payload;
    },
  },
});

export const { updateLogin, updateOverlay } = dataSlice.actions;
export default dataSlice.reducer;
